In [28]:
#ASSINGMENT_2 BY CYRIL THOMAS
#Author : DHANANJAY VYAS
#Date : 17-10-2024

In [29]:
# Load required libraries
import pandas as pd  # For data manipulation and analysis
from sklearn.model_selection import train_test_split  # For splitting data into training and testing sets
from sklearn.ensemble import RandomForestClassifier  # For implementing the Random Forest classification model
from sklearn.metrics import classification_report, accuracy_score  # For evaluating model performance

In [30]:
# Load the dataset from an Excel file
data = pd.read_excel("C:/Users/vyasd/Downloads/kepler_data.xlsx")
data

,# This file was produced by the NASA Exoplanet Archive http://exoplanetarchive.ipac.caltech.edu,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48
0,#,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,# COLUMN kepid: KepID,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,# COLUMN kepoi_name: KOI Name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,# COLUMN kepler_name: Kepler Name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,# COLUMN koi_disposition: Exoplanet Archive Di...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9611,10090151,K07985.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0,0,1,1,0,...,-166,4.529,0.035,-0.196,0.903,0.237,-0.079,297.18875,47.093819,14.082
9612,10128825,K07986.01,NaN,CANDIDATE,CANDIDATE,0.497,0,0,0,0,...,-220,4.444,0.056,-0.224,1.031,0.341,-0.114,286.50937,47.163219,14.757
9613,10147276,K07987.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.021,0,0,1,0,...,-236,4.447,0.056,-0.224,1.041,0.341,-0.114,294.16489,47.176281,15.385
9614,10155286,K07988.01,NaN,CANDIDATE,CANDIDATE,0.092,0,0,0,0,...,-128,2.992,0.03,-0.027,7.824,0.223,-1.896,296.76288,47.145142,10.998
9615,10156110,K07989.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0,0,0,1,1,...,-225,4.385,0.054,-0.216,1.193,0.41,-0.137,297.00977,47.121021,14.826

In [31]:
# Skip the first 51 rows to clean up the dataset
data_1 = data[51:]  # Keep the data starting from row 51
new_header = data_1.iloc[0]  # Use the first row of the data as the new header
data_2 = data_1[1:]  # Create a new DataFrame excluding the header row
data_2.columns = new_header  # Set the new header to the DataFrame
data_2

51,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
52,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1,0,0,0,0,...,-81,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
53,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,0,...,-81,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
54,10811496,K00753.01,NaN,CANDIDATE,CANDIDATE,0,0,0,0,0,...,-176,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
55,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0,0,1,0,0,...,-174,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.28521,15.597
56,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1,0,0,0,0,...,-211,4.438,0.07,-0.21,1.046,0.334,-0.133,288.75488,48.2262,15.509
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9611,10090151,K07985.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0,0,1,1,0,...,-166,4.529,0.035,-0.196,0.903,0.237,-0.079,297.18875,47.093819,14.082
9612,10128825,K07986.01,NaN,CANDIDATE,CANDIDATE,0.497,0,0,0,0,...,-220,4.444,0.056,-0.224,1.031,0.341,-0.114,286.50937,47.163219,14.757
9613,10147276,K07987.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.021,0,0,1,0,...,-236,4.447,0.056,-0.224,1.041,0.341,-0.114,294.16489,47.176281,15.385
9614,10155286,K07988.01,NaN,CANDIDATE,CANDIDATE,0.092,0,0,0,0,...,-128,2.992,0.03,-0.027,7.824,0.223,-1.896,296.76288,47.145142,10.998
9615,10156110,K07989.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0,0,0,1,1,...,-225,4.385,0.054,-0.216,1.193,0.41,-0.137,297.00977,47.121021,14.826

In [32]:
# Clean the dataset
data_cleaned = data_2[['kepoi_name', 'kepler_name', 'koi_disposition']].copy()
data_cleaned

51   kepoi_name   kepler_name koi_disposition
52    K00752.01  Kepler-227 b       CONFIRMED
53    K00752.02  Kepler-227 c       CONFIRMED
54    K00753.01           NaN       CANDIDATE
55    K00754.01           NaN  FALSE POSITIVE
56    K00755.01  Kepler-664 b       CONFIRMED
...         ...           ...             ...
9611  K07985.01           NaN  FALSE POSITIVE
9612  K07986.01           NaN       CANDIDATE
9613  K07987.01           NaN  FALSE POSITIVE
9614  K07988.01           NaN       CANDIDATE
9615  K07989.01           NaN  FALSE POSITIVE

[9564 rows x 3 columns]

In [33]:
# Ensure that the data types are correct
data_cleaned['kepoi_name'] = data_cleaned['kepoi_name'].astype(str) # Ensure kepoi_name is a string
data_cleaned['kepler_name'] = data_cleaned['kepler_name'].astype(str) # Ensure kepler_name is a string
data_cleaned['koi_disposition'] = data_cleaned['koi_disposition'].astype(str) # Ensure koi_disposition is a string

In [34]:
# One-hot encode categorical features
X = pd.get_dummies(data_cleaned[['kepler_name']], drop_first=True)  # Only encode kepler_name
y = data_cleaned['koi_disposition']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the Random Forest model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Print accuracy and classification report
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
print(classification_report(y_test, y_pred))

Accuracy: 0.75
                precision    recall  f1-score   support

     CANDIDATE       0.00      0.00      0.00       484
     CONFIRMED       1.00      1.00      1.00       490
FALSE POSITIVE       0.66      1.00      0.80       939

      accuracy                           0.75      1913
     macro avg       0.55      0.67      0.60      1913
  weighted avg       0.58      0.75      0.65      1913

D:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [35]:
# Create a DataFrame to hold the predictions alongside the original features
results = pd.DataFrame({
    'kepoi_name': data_cleaned.loc[X_test.index, 'kepoi_name'],
    'kepler_name': data_cleaned.loc[X_test.index, 'kepler_name'],
    'predicted_disposition': y_pred
})

# Create lists for each classification
candidate_planets = results[results['predicted_disposition'] == 'CANDIDATE'][['kepoi_name', 'predicted_disposition']]
confirmed_planets = results[results['predicted_disposition'] == 'CONFIRMED'][['kepoi_name', 'kepler_name', 'predicted_disposition']]
false_positive_planets = results[results['predicted_disposition'] == 'FALSE POSITIVE'][['kepoi_name', 'predicted_disposition']]

# Include planets with missing kepler_name in the final lists
missing_kepler_name = results[results['kepler_name'].isnull()][['kepoi_name', 'predicted_disposition']]

In [36]:
# Print the results
print("\nCandidate Planets:")
print(candidate_planets)

print("\nConfirmed Planets:")
print(confirmed_planets)

print("\nFalse Positive Planets:")
print(false_positive_planets)

print("\nPlanets without Kepler Name:")
print(missing_kepler_name)

Candidate Planets:
Empty DataFrame
Columns: [kepoi_name, predicted_disposition]
Index: []

Confirmed Planets:
     kepoi_name     kepler_name predicted_disposition
1194  K01751.01    Kepler-949 b             CONFIRMED
1484  K02049.01   Kepler-1072 b             CONFIRMED
1822  K02368.01   Kepler-1210 b             CONFIRMED
1108  K00188.01    Kepler-425 b             CONFIRMED
2464  K02951.01   Kepler-1393 b             CONFIRMED
...         ...             ...                   ...
1651  K01876.01    Kepler-991 b             CONFIRMED
402   K00975.01   Kepler-21 A b             CONFIRMED
5935  K04014.01   Kepler-1700 b             CONFIRMED
3020  K00298.01  Kepler-515 A b             CONFIRMED
616   K00949.01    Kepler-739 b             CONFIRMED

[490 rows x 3 columns]

False Positive Planets:
     kepoi_name predicted_disposition
9056  K06884.01        FALSE POSITIVE
5080  K03395.01        FALSE POSITIVE
1407  K01829.01        FALSE POSITIVE
8792  K07121.01        FALSE POSITIVE
3517  K00741.01        FALSE POSITIVE
...         ...                   ...
4418  K04587.01        FALSE POSITIVE
2312  K02618.01        FALSE POSITIVE
1262  K01527.01        FALSE POSITIVE
8192  K07199.01        FALSE POSITIVE
4556  K04688.01        FALSE POSITIVE

[1423 rows x 2 columns]

Planets without Kepler Name:
Empty DataFrame
Columns: [kepoi_name, predicted_disposition]
Index: []

In [48]:
print("1. Why did you choose the particular algorithm?\n")

print("I chose the Random Forest Classifier for this classification task due to its robustness and versatility.\nRandom Forest is an ensemble learning method that builds multiple decision trees and merges their results, which helps to improve accuracy and reduce the risk of overfitting. \nThis is particularly important when working with a dataset that may have noise or inconsistencies, as is often the case with astronomical data. \nAdditionally, Random Forest can handle categorical variables well, making it suitable for our dataset, which includes planet classifications.")

1. Why did you choose the particular algorithm?

I chose the Random Forest Classifier for this classification task due to its robustness and versatility.
Random Forest is an ensemble learning method that builds multiple decision trees and merges their results, which helps to improve accuracy and reduce the risk of overfitting.
This is particularly important when working with a dataset that may have noise or inconsistencies, as is often the case with astronomical data.
Additionally, Random Forest can handle categorical variables well, making it suitable for our dataset, which includes planet classifications.

In [54]:
print("2. What are the different tuning methods used for the algorithm?\n") 

print("To optimize the performance of the Random Forest model, we can use several tuning methods, including:\n\nGrid Search: This involves systematically testing a range of hyperparameter values to find the optimal combination. Key parameters to tune might include the number of trees (n_estimators), the maximum depth of the trees (max_depth), and the minimum samples required to split a node (min_samples_split).\n\nRandom Search: This is a more efficient alternative to Grid Search that randomly samples hyperparameter combinations instead of testing every possible combination.\n\nCross-Validation: Utilizing k-fold cross-validation can help assess how well the model generalizes to unseen data by splitting the training data into k subsets and validating the model k times.")

2. What are the different tuning methods used for the algorithm?

To optimize the performance of the Random Forest model, we can use several tuning methods, including:

Grid Search: This involves systematically testing a range of hyperparameter values to find the optimal combination. Key parameters to tune might include the number of trees (n_estimators), the maximum depth of the trees (max_depth), and the minimum samples required to split a node (min_samples_split).

Random Search: This is a more efficient alternative to Grid Search that randomly samples hyperparameter combinations instead of testing every possible combination.

Cross-Validation: Utilizing k-fold cross-validation can help assess how well the model generalizes to unseen data by splitting the training data into k subsets and validating the model k times.

In [55]:
print("3. Did you consider any other choice of algorithm? Why or why not?\n")

print("Yes, I considered several other algorithms such as Logistic Regression, Support Vector Machines (SVM), and Gradient Boosting Machines (GBM). However, I ultimately chose Random Forest because:\nLogistic Regression is limited to linear relationships and might not capture complex interactions between features well.\nSVM can be sensitive to the choice of kernel and may require more extensive tuning for performance, especially with larger datasets.\nGradient Boosting can be more accurate but is often more prone to overfitting and can take longer to train.\nGiven the need for a reliable and quick solution for our classification task, Random Forest struck a good balance between performance and ease of use.")

3. Did you consider any other choice of algorithm? Why or why not?

Yes, I considered several other algorithms such as Logistic Regression, Support Vector Machines (SVM), and Gradient Boosting Machines (GBM). However, I ultimately chose Random Forest because:
Logistic Regression is limited to linear relationships and might not capture complex interactions between features well.
SVM can be sensitive to the choice of kernel and may require more extensive tuning for performance, especially with larger datasets.
Gradient Boosting can be more accurate but is often more prone to overfitting and can take longer to train.
Given the need for a reliable and quick solution for our classification task, Random Forest struck a good balance between performance and ease of use.

In [57]:
print("4. What is the accuracy?\n")
print("The accuracy of the model is calculated using the formula:\nAccuracy=(Number of Correct Predictions/Total Predictions)")
print("In our code, we printed the accuracy score after evaluating the model on the test set. The exact accuracy value will depend on the dataset and can vary with different runs due to the randomness inherent in the Random Forest algorithm.")

4. What is the accuracy?

The accuracy of the model is calculated using the formula:
Accuracy=(Number of Correct Predictions/Total Predictions)
In our code, we printed the accuracy score after evaluating the model on the test set. The exact accuracy value will depend on the dataset and can vary with different runs due to the randomness inherent in the Random Forest algorithm.

In [58]:
print("5. What are the different types of metrics that can be used to evaluate the model?\n")

print("Several metrics can be used to evaluate the performance of a classification model:\n")

print("Accuracy: The ratio of correctly predicted instances to the total instances.\n\nPrecision: The ratio of true positive predictions to the total predicted positives, indicating how many of the predicted positive cases were actually correct.\n\nF1 Score: The harmonic mean of precision and recall, providing a balance between the two.\n\nConfusion Matrix: A table that summarizes the performance of the model by showing true positive, false positive, true negative, and false negative counts.\n\nThese metrics provide a comprehensive view of the model's performance, allowing us to understand its strengths and weaknesses better.")
print("By considering these factors, we can make informed decisions about the model's effectiveness and how to improve it further.")

5. What are the different types of metrics that can be used to evaluate the model?

Several metrics can be used to evaluate the performance of a classification model:

Accuracy: The ratio of correctly predicted instances to the total instances.

Precision: The ratio of true positive predictions to the total predicted positives, indicating how many of the predicted positive cases were actually correct.

F1 Score: The harmonic mean of precision and recall, providing a balance between the two.

Confusion Matrix: A table that summarizes the performance of the model by showing true positive, false positive, true negative, and false negative counts.

These metrics provide a comprehensive view of the model's performance, allowing us to understand its strengths and weaknesses better.
By considering these factors, we can make informed decisions about the model's effectiveness and how to improve it further.